config/routes.rb
Rails.application.routes.draw do
   get  'userrs/delete'
   get  'userrs/activate_account'
  resources :userrs
  get 'home/index'

  devise_for :users
  root to: "home#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_many :apms

 
end

app/models/apm.rb
class Apm < ActiveRecord::Base
  belongs_to :admin
  has_many :teamleads

 
end

app/models/employ.rb
class Employ < ActiveRecord::Base
  belongs_to :teamlead
end

app/models/teamlead.rb
class Teamlead < ActiveRecord::Base
  belongs_to :apm
  has_many :employs

  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_paranoid
  after_save :check_role

   def find_teamlead
    Apm.find_by_user_id(self.id).teamleads.map {|employs| User.find(apm.user_id)}
  end

  def find_employ
    Teamlead.find_by_user_id(self.id).employs.map {|apm| User.find(apm.user_id)}
  end

 

  def check_role
    if self.role == 'admin'
       if Admin.all.count == 0
         admin = Admin.new
         admin.user_id = self.id
         admin.save
       end
    elsif self.role == 'apm'
       apm = Apm.new
       apm.user_id = self.id
       apm.save
    elsif self.role == 'teamlead'
       teamlead = Teamlead.new
       teamlead.user_id = self.id
       teamlead.save
    else 
       employ = Employ.new
       employ.user_id = self.id
       employ.save
    end
  end

  def admin?
    if self.role == 'admin'
    	return true
    end
  end

  def employ?
    if self.role == 'employ'
    	return true 
    end
  end

  def apm?
    if self.role == 'apm'
    	return true
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/custom_users_controller.rb
class CustomUsersController < ApplicationController
	before_filter :authenticate_user! 

  def index
  	@users = if current_user.role == 'admin'
  	         #  @users = (current_user.blank? ? User.all : User.find(:all, :conditions => ["id != ?", current_user.id]))
  		       @users = User.all
             @users.delete current_user
             @users.to_ary
             elsif current_user.role == 'apm'
  		       	  current_user.find_teamlead
  		       elsif current_user.role == 'teamlead'
  		       	  current_user.find_employ
  		       else 
  		       	  current_user
  		       end
  	@user = User.only_deleted # to find deleted user
  end

  def new
    @user = User.new
  end

  def create
  	@user = User.new
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]
    @user.role = params[:user][:role]

		respond_to do |format|
			if @user.save
				format.html { redirect_to :controller=>'custom_users',:action=>'index', notice: 'User was successfully created.' }
			else
			  format.html { render :new , notice: 'error creating user created.' }
			end
		end
  
  end

  def activate_account
    User.restore(params[:id])
    redirect_to :controller=>'custom_users',:action=>'index'
  end

  def delete
    user = User.find(params[:id])
    user.delete
    redirect_to :controller=>'custom_users',:action=>'index'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user! 
  def index
  end
end

app/controllers/userrs_controller.rb
class UserrsController < ApplicationController
	before_filter :authenticate_user! 

  def index
  	@users = if current_user.role == 'admin'
  		          current_user.find_apm
  		       elsif current_user.role == 'apm'
  		       	  current_user.find_teamlead
  		       elsif current_user.role == 'teamlead'
  		       	  current_user.find_employ
  		       else 
  		       	  current_user
  		       end
  	@user = User.only_deleted # to find deleted user
  end

  def new
    @user = User.new
  end

  def create
  	@user = User.new
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]
    @user.role = params[:user][:role]

		respond_to do |format|
			if @user.save
				format.html { redirect_to :controller=>'userrs',:action=>'index', notice: 'User was successfully created.' }
			else
			  format.html { render :new , notice: 'error creating user created.' }
			end
		end
  
  end

  def activate_account
    User.restore(params[:id])
    redirect_to :controller=>'userrs',:action=>'index'
  end

  def delete
    user = User.find(params[:id])
    user.delete
    redirect_to :controller=>'userrs',:action=>'index'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/userrs_helper.rb
module UserrsHelper
end

app/views/custom_users/index.html.erb
<h2>Listing User</h2>
<table class = "table">
  <tr>
    <th>Email</th>
    <th>Role</th>
    <th>Action</th>
  </tr>

  <% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.role %></td>
    <td><%= link_to 'destroy' ,  custom_users_delete_path(:id => user.id), data: { confirm: 'Are you sure?' }%></td>
  </tr>
  <% end %>
</table>

<%= link_to 'New User' , new_custom_user_path %>

<h2>Listing Deleted User</h2>
<table class = "table">
  <tr>
    <th>Email</th>
    <th>Role</th>
    <th>Activate</th>
  </tr>

  <% @user.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.role %></td>
    <td><%= link_to 'activate' , custom_users_activate_account_path(:id => user.id), data: { confirm: 'Are you sure?' }%></td>
  </tr>
  <% end %>
</table>

app/views/custom_users/new.html.erb
<h2>New User</h2>
<%= form_for @user ,:url => custom_users_path do |f| %>
  <div>
    <%= f.label :email%><br/>
    <%= f.email_field :email%>
  </div>

  <div>
    <%= f.label :password%><br/>
    <%= f.password_field :password%>
  </div>

  <div>
    <%= f.label :confirm_password%><br/>
    <%= f.password_field :password_confirmation%>
  </div>

  <div>
    <%= f.label :role%>
    <%= f.select :role, options_for_select(%w[admin employ apm teamlead] , selected: "employ", disabled: "admin") %>
  </div>
  
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PmsTrigma" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">PmsTrigma</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Users", userrs_path  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete if user_signed_in? %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/userrs/index.html.erb
<h2>Listing User</h2>
<table class = "table">
  <tr>
    <th>Email</th>
    <th>Role</th>
    <th>Action</th>
  </tr>

  <% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.role %></td>
    <td><%= link_to 'destroy' ,  userrs_delete_path(:id => user.id), data: { confirm: 'Are you sure?' }%></td>
  </tr>
  <% end %>
</table>

<%= link_to 'New User' , new_userr_path %>

<h2>Listing Deleted User</h2>
<table class = "table">
  <tr>
    <th>Email</th>
    <th>Role</th>
    <th>Activate</th>
  </tr>

  <% @user.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.role %></td>
    <td><%= link_to 'activate' , userrs_activate_account_path(:id => user.id), data: { confirm: 'Are you sure?' }%></td>
  </tr>
  <% end %>
</table>

app/views/userrs/new.html.erb
<h2>New User</h2>
<%= form_for @user ,:url => userrs_path do |f| %>
  <div>
    <%= f.label :email%><br/>
    <%= f.email_field :email%>
  </div>

  <div>
    <%= f.label :password%><br/>
    <%= f.password_field :password%>
  </div>

  <div>
    <%= f.label :confirm_password%><br/>
    <%= f.password_field :password_confirmation%>
  </div>

  <div>
    <%= f.label :role%>
    <%= f.select :role, options_for_select(%w[admin apm teamlead employ]) %>
  </div>
  
  <div>
    <%= f.submit %>
  </div>
<% end %>